
genesis-file="/config/genesis.json"
node-private-key-file="/opt/besu/keys/nodekey"
logging="INFO"
data-path="/data"
host-allowlist=["*"]
min-gas-price=0

# All methods ["EEA","WEB3","ETH","NET","TRACE","DEBUG","ADMIN","TXPOOL","PRIV","PERM","QBFT"]

# rpc
rpc-http-enabled=true
rpc-http-host="0.0.0.0"
rpc-http-port=8545
rpc-http-cors-origins=["*"]
rpc-http-api=["ETH","WEB3","NET","ADMIN","TXPOOL","QBFT","PERM","PRIV","EEA","DEBUG","TRACE"]
rpc-http-api-method-no-auth=["admin_nodeInfo","admin_peers",
    "net_peerCount","net_enode","net_listening","net_peerCount","net_services","net_version","web3_clientVersion","web3_sha3",
    "txpool_besuTransactions","qbft_getValidatorsByBlockNumber","qbft_getPendingVotes",
    "eth_getQuorumPayload","eth_accounts","eth_blockNumber","eth_call","eth_chainId","eth_coinbase","eth_estimateGas","eth_feeHistory","eth_gasPrice","eth_getBalance",
    "eth_getBlockByHash","eth_getBlockByNumber","eth_getBlockTransactionCountByHash","eth_getBlockTransactionCountByNumber","eth_getCode","eth_getFilterChanges",
    "eth_getFilterLogs","eth_getLogs","eth_getMinerDataByBlockHash","eth_getMinerDataByBlockNumber","eth_getProof","eth_getStorageAt",
    "eth_getTransactionByBlockHashAndIndex", "eth_getTransactionByBlockNumberAndIndex","eth_getTransactionByHash","eth_getTransactionCount","eth_getTransactionReceipt",
    "eth_getUncleByBlockHashAndIndex","eth_getUncleByBlockNumberAndIndex","eth_getUncleCountByBlockHash","eth_getUncleCountByBlockNumber","eth_getWork","eth_hashrate",
    "eth_mining","eth_newBlockFilter","eth_newFilter","eth_newPendingTransactionFilter","eth_protocolVersion","eth_sendRawPrivateTransaction","eth_sendRawTransaction",
    "eth_sendTransaction","eth_submitHashrate","eth_submitWork","eth_subscribe","eth_syncing","eth_uninstallFilter","eth_unsubscribe",
    "priv_call","priv_getPrivateTransaction","priv_getTransactionCount","priv_getPrivacyPrecompileAddress","priv_getTransactionReceipt","priv_createPrivacyGroup",
    "priv_deletePrivacyGroup","priv_findPrivacyGroup","priv_debugGetStateRoot","priv_distributeRawTransaction","priv_getEeaTransactionCount","priv_getCode",
    "priv_getLogs","priv_newFilter","priv_uninstallFilter","priv_getFilterChanges","priv_getFilterLogs","priv_subscribe","priv_unsubscribe","privx_findOnchainPrivacyGroup",
    "privx_findFlexiblePrivacyGroup","eea_sendRawTransaction","debug_traceTransaction","trace_replayBlockTransactions","trace_block","trace_transaction"
]
rpc-http-authentication-enabled=true
rpc-http-authentication-jwt-public-key-file="/opt/besu/keys/rpcPublicKey.pem"

# ws
rpc-ws-enabled=true
rpc-ws-host="0.0.0.0"
rpc-ws-port=8546
rpc-ws-api=["ETH"]

# graphql
graphql-http-enabled=false

# metrics
metrics-enabled=true
metrics-host="0.0.0.0"
metrics-port=9545

# permissions
permissions-nodes-config-file-enabled=false
#permissions-nodes-config-file="/config/permissions_config.toml"

# bootnodes
bootnodes=[
    "enode://ea7633d1362780ed8bce54a33650e5da8c71ef66aa7e6b270d6371c4dbc4dfabdcf332bf89f5e8d313cc2362fe9cf14b011055b6a573b76455ac347219cc1dba@13.38.237.167:30303",
    "enode://6368c830c77c8f552a69d2fee01e808f94e7f004048b974de806172f60309a42222dd44c0dbd985806f12edefe736669836671ed4d66495efc4d46b08063c51d@15.188.189.40:30303",
    "enode://998e22637bfce56203df62ead805bf57cde9b12527cf679f36b3b3573ecddd1441d38baf294449fafba8ab981d2970824752b77ea2e14534b5b7d88d2949f9a6@35.180.249.167:30303"
]

# Discovery at boot is set to a list of static files, but will also discover new nodes should they be added
# static nodes
# static-nodes-file="/config/static-nodes.json"
discovery-enabled=true
